### ISSUE TITLE
PDF link in readme doesn't work

### ISSUE THREAD

**Issue by sytelus** [stas00/ml-engineering#73]
You might want to change the link from 

https://huggingface.co/stas/ml-engineering-book/resolve/main/Stas%20Bekman%20-%20Machine%20Learning%20Engineering.pdf?download=true

to

https://huggingface.co/stas/ml-engineering-book/resolve/main/Stas%20Bekman%20-%20Machine%20Learning%20Engineering.pdf

Or even better, put the pdf copy in releases.

**Comment by stas00** [comment]
I don't know what to do with "PDF link in readme doesn't work" - please explain specifically what problem are you running into.

I have just retested - either link style works for me.

**Comment by sytelus** [comment]
Hmmm... First link worked in Edge but not on Chrome. May be this is issue on my side. I will close this for now, however, it would be great to have pdf in releases!

**Comment by stas00** [comment]
Thank you for clarifying, @sytelus 

Actually, I have tested pasting directly:
`https://huggingface.co/stas/ml-engineering-book/blob/main/Stas%20Bekman%20-%20Machine%20Learning%20Engineering.pdf` into FF and it's not giving me the pdf, but takes me to the hub page. so `?download=true` is needed.

There can be no pdf in releases since they are no releases, this is a live book - I push when I have some updates to push and I update the pdf once in a few weeks or so.
