### ISSUE TITLE
Minor Typo in emulate multi node

### ISSUE THREAD

**Issue by anindya-saha** [stas00/ml-engineering#8]
Please add `import torch.distributed as dist` in  the section
**4. Create a test script to check both GPUs are used.**

I tried creating a branch and raise a PR but could not do so due to 
```
$:~/ml-engineering-stats00$ git push origin asaha/emulate-multi-node
remote: Permission to stas00/ml-engineering.git denied to anindya-saha.
fatal: unable to access 'https://github.com/stas00/ml-engineering.git/': The requested URL returned error: 403
```

**Comment by stas00** [comment]
Thank you for flagging, Anindya - as you suggested fixed in:
https://github.com/stas00/ml-engineering/commit/a6aa601cea6d429b3e2a21dbde9413e360c759eb

**Comment by stas00** [comment]
You can't create a branch on someone else's repo. You have to clone it first, please see: https://github.com/stas00/git-tools/tree/master/how-to-make-pr

**Comment by anindya-saha** [comment]
Thank you @stas00 . I meant I cloned, created a branch. Then wanted to push on that branch and create a PR. But could not push to that branch due to lack of permission. Anyway, since you already added, its sorted.

I was able to simulate 2 nodes on a GCP m/c following your code. I did have to do some additional trick with the public keys to enable passwordless ssh, but overall I followed your steps to test out the multi node simulation on a single m/c.

**Comment by stas00** [comment]
Something must have gone haywire, since others have already made PRs into this repo https://github.com/stas00/ml-engineering/pulls?q=is%3Apr+is%3Aclosed - if you make another PR in the future and it happens again let's look together at why this is happening for you. 

For simple one file small fixes I usually just do it directly in github - open the file -> edit -> make PR - much faster.

Glad to hear it worked, Anindya. If you feel the trick you refer to might be useful to others please don't hesitate to PR it as well. and thank you!
